# Generated by Django 4.0.4 on 2022-06-04 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task6', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='zip',
        ),
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='task6.people'),
            preserve_default=False,
        ),
    ]
