# Generated by Django 4.0.4 on 2022-06-04 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task6', '0002_remove_address_zip_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
