# Generated by Django 4.0.5 on 2022-06-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task6', '0003_remove_product_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupants_name', models.CharField(max_length=50)),
                ('room_number', models.IntegerField()),
                ('amount_paid', models.IntegerField()),
                ('occupants_email', models.EmailField(max_length=254)),
                ('occupants_job', models.CharField(max_length=50)),
                ('number_of_nights', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
    ]
